name: Full CI/CD with Terraform, Ansible, K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform + Ansible Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Workspace
        working-directory: ./terraform
        run: |
          WORKSPACE="${GITHUB_REF##*/}"
          terraform workspace select "$WORKSPACE" || terraform workspace new "$WORKSPACE"
          echo "TF_VAR_environment=$WORKSPACE" >> $GITHUB_ENV

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Get EC2 Public IP
        working-directory: ./terraform
        run: |
          IP=$(terraform output -raw ec2_public_ip)
          echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV

      - name: Debug IP
        run: echo "Server IP is $EC2_PUBLIC_IP"

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > test.pem
          chmod 600 test.pem

      - name: Run Ansible Playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ./ansible/playbook.yml \
          -i "$EC2_PUBLIC_IP," \
          --user ubuntu \
          --private-key test.pem