name: Full CI/CD with Terraform, Ansible, K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform + Ansible Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Workspace
        working-directory: ./terraform
        run: |
          WORKSPACE="${GITHUB_REF##*/}"
          terraform workspace select "$WORKSPACE" || terraform workspace new "$WORKSPACE"
          echo "TF_VAR_environment=$WORKSPACE" >> $GITHUB_ENV
          export ANSIBLE_HOST_KEY_CHECKING=False

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
      

      

