##f
name: Full CI/CD with Terraform, Ansible, K3s

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Select Terraform Workspace & Set Environment
        run: |
         # Use branch name directly as workspace
         WORKSPACE="${GITHUB_REF##*/}"

         echo "Using Terraform workspace: $WORKSPACE"

         # Select existing workspace or create new one
         terraform workspace select "$WORKSPACE" || terraform workspace new "$WORKSPACE"
     
         # Set Terraform environment variable
         export TF_VAR_environment="$WORKSPACE"



      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Get EC2 Public IP
        working-directory: ./terraform
        run: |
          PUBLIC_IP=$(terraform output -raw ec2_public_ip | tr -d '\n')
          printf "EC2_PUBLIC_IP=%s\n" "$PUBLIC_IP" >> $GITHUB_ENV
          echo "ec2_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT

      - name: Debug IP
        run: echo "IP is $EC2_PUBLIC_IP"

  ansible-install-k3s:
    name: Install K3s via Ansible
    runs-on: self-hosted
    needs: terraform-apply
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > test.pem
          sudo chmod 600 test.pem
      
      - name: Run Ansible Playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ./ansible/playbook.yml \
          -i "${{ needs.terraform-apply.outputs.PUBLIC_IP }}," \
          --user ubuntu \
          --private-key test.pem
                
  build-and-push-docker:
    name: Build & Push Docker Image
    runs-on: self-hosted
    needs: ansible-install-k3s
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx26:v2 ./app

      - name: Push Docker Image
        run: sudo docker push ${{ secrets.DOCKER_USERNAME }}/nginx26:v2

  deploy-to-k3s:
    name: Deploy to K3s Cluster
    runs-on: self-hosted
    needs: build-and-push-docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > test.pem
          sudo chmod 600 test.pem
          
      - name: Copy Kubeconfig from EC2
        run: scp -o StrictHostKeyChecking=no -i test.pem ubuntu@${{ needs.terraform-apply.outputs.PUBLIC_IP }}:/etc/rancher/k3s/k3s.yaml ./kubeconfig

      - name: Deploy App
        env:
          KUBECONFIG: ./kubeconfig
        run: |
          kubectl apply -f ./k3s-project/k3s/deploy.yml
          kubectl apply -f ./k3s-project/k3s/k3s/svc.yml
          kubectl apply -f ./k3s-project/k3s/k3s/ingress.yml